# Site settings
title: Hi, I'm Dominik.
description: Dominik Haitz' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mateusz Jabłoński
user_title: 
user_job_title: Software License Data Analyst
email: mateuszj2312 [at] gmail.com
twitter_username: d_haitz
github_username:  dhaitz

exclude: ['package.json', 'src' , 'node_modules']
