# Site settings
title: Hi, I'm Mateusz.
description: Mateusz Jablonski' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mateusz Jabłoński
user_title: 
user_job_title: IT Asset Manager
email: mateuszj2312@gmail.com
twitter_username: J
github_username:  matJablo

exclude: ['package.json', 'src' , 'node_modules']
